use_frameworks!

platform :ios, '10.0'

target 'RCSPrivateFramework_Example' do
  pod 'RCSPrivateFramework', :path => '../'

  target 'RCSPrivateFramework_Tests' do
    inherit! :search_paths

    
  end
end
